// What each monthly-planner tool covers, so "Find a tool" matches topics as
// well as names (e.g. "noi" finds every tool that shows NOI).
export const toolTopics: Record<string, string[]> = {
  overview: [
    "NOI",
    "net operating income",
    "IRR",
    "XIRR",
    "equity multiple",
    "DSCR",
    "cash flow",
    "summary",
    "returns",
  ],
  report: [
    "report",
    "print",
    "PDF",
    "NOI",
    "IRR",
    "capital recovery",
    "distributions",
    "summary",
  ],
  decisionlab: [
    "breakeven",
    "asking price",
    "offer",
    "lenders",
    "financing",
    "refinance",
    "DSCR",
    "compare",
  ],
  reconciliation: [
    "workbook",
    "benchmark",
    "spreadsheet",
    "Excel",
    "NOI",
    "XIRR",
    "variance",
    "compare",
  ],
  calendar: ["lease", "renewal", "expiration", "timeline", "dates", "delivery"],
  units: [
    "rent roll",
    "units",
    "rent",
    "market rent",
    "lease",
    "renewal",
    "vacancy",
    "occupancy",
  ],
  monthly: [
    "cash flow",
    "funding",
    "NOI",
    "monthly",
    "reserves",
    "shortfall",
    "distributions",
  ],
  finance: [
    "loan",
    "debt",
    "interest rate",
    "DSCR",
    "debt yield",
    "LTV",
    "refinance",
    "amortization",
    "mortgage",
    "draws",
  ],
  development: [
    "construction",
    "development",
    "budget",
    "capex",
    "draws",
    "costs",
  ],
  expenses: [
    "expenses",
    "operating costs",
    "opex",
    "taxes",
    "insurance",
    "management",
    "utilities",
    "repairs",
  ],
  imports: [
    "import",
    "CSV",
    "XLSX",
    "Excel",
    "spreadsheet",
    "rent roll",
    "upload",
    "mapping",
  ],
  actuals: ["actuals", "variance", "NOI", "budget vs actual", "performance"],
  detail: ["operating records", "ledger", "income", "expenses", "transactions"],
  returns: [
    "investors",
    "waterfall",
    "promote",
    "partners",
    "tax",
    "depreciation",
    "IRR",
    "XIRR",
    "distributions",
  ],
  risk: [
    "stress",
    "sensitivity",
    "tornado",
    "Monte Carlo",
    "probability",
    "downside",
    "exit cap",
    "scenarios",
  ],
  diligence: ["evidence", "diligence", "documents", "attachments", "files"],
  sources: ["assumptions", "sources", "inputs", "provenance"],
  decisions: ["decisions", "case study", "notes"],
  portfolio: ["portfolio", "backup", "restore", "projects", "export"],
};

/** "" when the name matches, the first matching topic, or null for no match. */
export function toolMatch(id: string, label: string, query: string) {
  const q = query.trim().toLowerCase();
  if (!q || label.toLowerCase().includes(q)) return "";
  return toolTopics[id]?.find((t) => t.toLowerCase().includes(q)) ?? null;
}
